apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
secretGenerator:
- files:
  - loki.yaml=loki-conf.yaml
  name: loki
  namespace: logging
  behavior: replace
  type: Opaque
patchesStrategicMerge:
- loki-patch.yaml
resources:
- namespace.yaml
- loki.yaml
- promtail.yaml
