apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: logging
  labels:
    app: loki
    chart: loki-0.30.1
    release: loki
    heritage: Helm
  annotations:
    {}
spec:
  volumeClaimTemplates: []
