---
# Source: promtail/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: promtail
    chart: promtail-0.23.2
    heritage: Helm
    release: promtail
  name: promtail
  namespace: logging
