apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: k8s
      valueFiles:
        - values.yaml
    path: helm/grafana
    repoURL: https://github.com/meznyx/kubernetes.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
