apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/prometheus-community/kube-prometheus-stack/crds
    repoURL: https://github.com/meznyx/kubernetes.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - Replace=true
    automated:
      selfHeal: true
      prune: true
